import type { Topic } from "./types"

export const topics: Topic[] = [
  // Lead Fraud Topics
  {
    id: "1",
    title: "Lead Gen Form-Filling Fraud",
    keywords: ["lead generation", "form filling", "fraud detection", "fake submissions", "bot detection"],
    description: "Fraudulent activities related to automated form filling for lead generation",
    trendScore: 92,
    trending: true,
  },
  {
    id: "2",
    title: "Bot-Driven Fake Lead Generation",
    keywords: ["bots", "fake leads", "automated fraud", "lead quality", "verification systems"],
    description: "How bots are used to generate fake leads that appear legitimate",
    trendScore: 88,
    trending: true,
  },
  {
    id: "3",
    title: "Lead Gen Affiliate Fraud",
    keywords: ["affiliate marketing", "lead fraud", "commission fraud", "fake referrals", "traffic validation"],
    description: "Fraudulent practices in affiliate marketing related to lead generation",
    trendScore: 85,
    trending: true,
  },
  {
    id: "4",
    title: "Click Farms & Click Injection",
    keywords: ["click farms", "click injection", "ad fraud", "fake engagement", "traffic quality"],
    description: "Organized operations that generate fraudulent clicks and engagement",
    trendScore: 87,
    trending: true,
  },
  {
    id: "5",
    title: "Out-of-Geo & Misattributed Leads",
    keywords: ["geolocation", "misattribution", "location spoofing", "lead quality", "geographic targeting"],
    description: "Leads that appear to come from one location but actually originate elsewhere",
    trendScore: 82,
    trending: true,
  },
  {
    id: "6",
    title: "Spoofed or Synthetic Identity Submissions",
    keywords: ["identity fraud", "synthetic identities", "spoofing", "fake profiles", "identity verification"],
    description: "Creation and use of fake or synthetic identities for fraudulent lead submissions",
    trendScore: 84,
    trending: true,
  },
  // AI/AGI Topics
  {
    id: "7",
    title: "Agentic AI Systems",
    keywords: ["autonomous agents", "goal-oriented AI", "AI planning", "multi-agent systems", "agent foundations"],
    description: "AI systems that can act independently to achieve goals on behalf of users",
    trendScore: 95,
    trending: false,
  },
  {
    id: "8",
    title: "AGI Safety & Alignment",
    keywords: ["AI alignment", "safety measures", "ethical AI", "value alignment", "AI governance"],
    description: "Ensuring that artificial general intelligence systems act in accordance with human values",
    trendScore: 92,
    trending: false,
  },
  {
    id: "9",
    title: "Large Language Model Agents",
    keywords: ["LLM agents", "language models", "GPT", "reasoning", "tool use"],
    description: "Using large language models as the foundation for autonomous agents",
    trendScore: 90,
    trending: false,
  },
  {
    id: "10",
    title: "Multi-Agent Collaboration",
    keywords: [
      "agent collaboration",
      "swarm intelligence",
      "emergent behavior",
      "agent communication",
      "collective intelligence",
    ],
    description: "Systems where multiple AI agents work together to solve complex problems",
    trendScore: 88,
    trending: false,
  },
  {
    id: "11",
    title: "AI Reasoning & Planning",
    keywords: ["chain-of-thought", "tree-of-thought", "planning algorithms", "causal reasoning", "decision making"],
    description: "Advanced reasoning and planning capabilities in AI systems",
    trendScore: 85,
    trending: false,
  },
  {
    id: "12",
    title: "Tool-Using AI",
    keywords: ["tool use", "API integration", "function calling", "code execution", "augmented LLMs"],
    description: "AI systems that can use external tools and APIs to accomplish tasks",
    trendScore: 87,
    trending: false,
  },
]
